- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: all
  tasks:

    - name: Hello World
      debug:
        msg: "Hello World"

    - name: Show password
      debug:
        var: var_password
      ignore_errors: true

    - name: Show IP address
      debug:
        var: var_ipaddress
      ignore_errors: true